---
title: "hw05"
author: "Cody Grainger"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r}
library(tidyverse)
```


### Plot 1

Scatterplot displaying the trees dataset
```{r}
data(trees)
?trees

ggplot(data=trees)+
  geom_point(mapping=aes(x=Height,y=Girth))
```

### Plot 2

```{r}
data(lynx)
?lynx

#creating a vector for years 1821-1934
year <- c(1821:1934)
year

#inspecting the class of the lynx data set
class(lynx)
# the class is "time series"

#converting ts to vector
pelts <- as.vector(lynx)
pelts

#creating a data frame with pelts and year
lynxDF <- data.frame(year,pelts)
lynxDF

#plotting with ggplot. A maroon linechart
ggplot(data=lynxDF)+
  geom_line(mapping=aes(x=year,y=pelts),color="Maroon",size=1)
```

### Plot 3
```{r}
#iris data set
data(iris)

?iris

#iris scatter plot with modified labels
ggplot(data=iris)+
  geom_point(mapping=aes(x=Petal.Length,y=Petal.Width)) +
  labs(x="Petal Length", y = "Petal Width")
```

##### Plots 4 and 5
Violin plots use geometric shapes with varying widths throughout to represent data density. The widest part of any one violin plot object represents the median of the data set. The wider the figure the higher the density of data points that fall within those corresponding values
```{r}
#msleep data set
data(msleep)
?msleep

#Plot 4
#A violin plot with fill set to gray30
ggplot(data=msleep) +
  geom_violin(mapping=aes(x=vore,y=sleep_rem),fill="gray30")

#Plot 5
#A violin plot with fill set to gray70
ggplot(data=msleep) +
  geom_violin(mapping=aes(x=vore,y=sleep_rem),fill="gray70")
```





