---
title: "HW 08: More Data Wrangling"
author: "Cody Grainger"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- Change "your name" in the YAML header above to your name.

- As usual, enter the examples in code chunks and run them, unless told otherwise.

## Chapter 5: Data transformation

Read [R4ds Chapter 5: Data transformation](https://r4ds.had.co.nz/transform.html), sections 5-7.

**You do not answer any of the questions this week.** Just read and run all of the examples as noted below. Pay attention to the code you enter for the examples. You will be applying the information in future assignments.

### Section 5.5: Add new variables with `mutate()`

Type and run all of the examples.

Pay careful attention to the useful creation functions in section 5.5.1. 

### Section 5.6: Grouped summaries with `summarise()`

Read and run all of the examples. Pay careful attention to the useful summary functions. Unless you really like baseball, skip the baseball part of 5.6.3.

### Section 5.7: Grouped mutates (and filters)

Read and run all of the examples.
